package ru.gb.file.manager.core;

public enum CommandTypes {
    AUTH_REQUEST,
    CLIENT_DISCONNECT_REQUEST,
    CLIENT_FILE_TRANSFER,
    CLIENT_FILE_REQUEST,
    CLIENT_REQUEST_MKDIR,
    CLIENT_REQUEST_TOUCH,
    CLIENT_REQUEST_DELETE,
    CLIENT_REQUEST_PATH_GO_IN,
    CLIENT_REQUEST_PATH_GO_UP,
    CLIENT_REQUEST_RENAME,
    CLIENT_REQUEST_ALL_USERS,
    CLIENT_REQUEST_FILE_DELETE,
    CLIENT_REQUEST_FILE_SHARE,
    FILE_TRANSFER,
    SERVER_RESPONSE_FILE_LIST,
    SERVER_RESPONSE_TXT_MESSAGE,
    SERVER_RESPONSE_REGISTERED_USERS,
    FILE_MODEL;

}
