package ru.gb.file.manager.core;

public enum CommandTypes {
    AUTH_REQUEST,
    CLIENT_FILE_TRANSFER,
    CLIENT_FILE_REQUEST,
    CLIENT_REQUEST_MKDIR,
    CLIENT_REQUEST_TOUCH,
    CLIENT_REQUEST_PATH_GO_IN,
    CLIENT_REQUEST_PATH_GO_UP,
    CLIENT_REQUEST_FILE_RENAME,
    CLIENT_REQUEST_FILE_DELETE,
    SERVER_RESPONSE_FILE,
    SERVER_RESPONSE_FILE_LIST,
    SERVER_RESPONSE_TXT_MESSAGE,
    FILE_MODEL
}
